version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "assecoAssignment"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build: .
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=WarehouseDB;User Id=sa;Password=assecoAssignment;TrustServerCertificate=True;"
    ports:
      - "8080:80"
    networks:
      - backend

networks:
  backend:

volumes:
  sql_data:
