name: .NET

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build excluding .sqlproj
      run: |
        dotnet build --no-restore -p:ExcludeProjectFromBuild="WarehouseDB"
        # Replace "YourSqlProjectName" with the actual name of the .sqlproj project to exclude
        # Alternatively, if you need to exclude multiple projects, you might need to adjust the solution configuration

    - name: Run tests
      run: dotnet test --no-build
